### ISSUE TITLE
docker-compose快速搭建 Prometheus+Grafana监控系统

### ISSUE THREAD

**Issue by TFdream** [TFdream/docker-learning#4]
Prometheus负责收集数据，Grafana负责展示数据。

## 二、添加配置文件
```
mkdir -p ~/Ricky/Monitor/prometheus/config
cd ~/Ricky/Monitor/prometheus/config
```
### 2.1 添加prometheus.yml配置文件
```
vim prometheus.yml
```
增加如下配置：
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'demo-application'
    # 采集地址
    metrics_path: '/actuator/prometheus'
    # 目标服务器
    static_configs:
    - targets: ['127.0.0.1:8080']
```

## 三、编写docker-compose
```
$ cd ~/Ricky/Monitor/
$ vim docker-compose-monitor.yml
```
内容如下：
```
version: "3"

services:

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        hostname: prometheus
        restart: always
        networks:
            - frontend
        volumes:
            - ~/Ricky/Monitor/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ~/Ricky/Monitor/prometheus/data:/prometheus
        ports:
            - "9090:9090"
        command:
              - '--config.file=/etc/prometheus/prometheus.yml'
              - '--storage.tsdb.path=/prometheus'

    grafana:
        image: grafana/grafana
        container_name: grafana
        hostname: grafana
        restart: always
        networks:
            - frontend
        ports:
            - "3000:3000"
        volumes:
            - ~/Ricky/Monitor/grafana/data:/var/lib/grafana

    prometheus-demo:
        image: tfdream/spring-boot-prometheus-demo:1.0.0-SNAPSHOT
        container_name: prometheus-demo
        hostname: prometheus-demo
        restart: always
        networks:
            - frontend
        ports:
          - 8080:8080

networks:
  frontend:
    driver: bridge

```

## 四、启动docker-compose
```
#启动容器：
docker-compose -f docker-compose-monitor.yml -p monitor up -d
#停止容器：
docker-compose stop monitor
#删除容器
docker-compose -f docker-compose-monitor.yml down
```

## 参考资料
* [docker-compose快速搭建 Prometheus+Grafana监控系统](https://juejin.cn/post/6844903809517371406)
*
